// flow-typed signature: eeb6cd7b2d95159f3447add87da18a96
// flow-typed version: <<STUB>>/prism-themes_v0.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prism-themes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prism-themes' {
  declare module.exports: any;
}
